[tool.poetry]
name = "arduino-lint"
version = "0.0.0"
description = "arduino-lint"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

# Integration tests dependencies.
invoke = "^1.7.0"
pytest = "^7.1.1"
python-dateutil = "^2.8.2"
semver = "^2.13.0"

# Documentation generation dependencies.
gitpython = "^3.1.27"
mdx_truly_sane_lists = "^1.2"
mike = "^1.1.2"
mkdocs = "^1.2.3"
mkdocs-material = "^8.2.7"

[tool.poetry.dev-dependencies]
black = "^22.1"
codespell = "^2.1.0"
flake8 = "^4.0.1"
pep8-naming = "^0.12.1"

[tool.black]
line-length = 120
target-version = ["py38"]
