[tool.poetry]
name = "arduino-lint"
version = "0.0.0"
description = "arduino-lint"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

# Integration tests dependencies.
invoke = "^1.5.0"
pytest = "^6.2.5"
python-dateutil = "^2.8.2"
semver = "^2.13.0"

# Documentation generation dependencies.
gitpython = "^3.1.20"
mdx_truly_sane_lists = "^1.2"
mike = "^1.0.1"
mkdocs = "^1.2.1"
mkdocs-material = "^7.2.5"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
codespell = "^2.1.0"
flake8 = "^3.9.2"
pep8-naming = "^0.12.1"

[tool.black]
line-length = 120
target-version = ["py38"]
