[tool.poetry]
name = "arduino-lint"
version = "0.0.0"
description = "arduino-lint"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

# Integration tests dependencies.
invoke = "^2.2.0"
pytest = "^7.4.2"
python-dateutil = "^2.8.2"
semver = "^3.0.1"

# Documentation generation dependencies.
gitpython = "^3.1.37"
mdx_truly_sane_lists = "^1.3"
mike = "^1.1.2"
mkdocs = "^1.5.3"
mkdocs-material = "^9.4.3"

[tool.poetry.dev-dependencies]
black = "^23.9"
codespell = "^2.2.6"
flake8 = "^6.1.0"
pep8-naming = "^0.13.3"

[tool.black]
line-length = 120
target-version = ["py38"]
