# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/publish-go-tester-task.md
name: Publish Tester Build

# See: https://docs.github.com/actions/reference/workflows-and-actions/events-that-trigger-workflows
on:
  create:
  push:
    paths:
      - ".github/workflows/publish-go-tester-task.ya?ml"
      - "go.mod"
      - "go.sum"
      - "Taskfile.ya?ml"
      - "DistTasks.ya?ml"
      - "**.go"
  pull_request:
    paths:
      - ".github/workflows/publish-go-tester-task.ya?ml"
      - "go.mod"
      - "go.sum"
      - "Taskfile.ya?ml"
      - "DistTasks.ya?ml"
      - "**.go"
  workflow_dispatch:
  repository_dispatch:

env:
  # As defined by the Taskfile's PROJECT_NAME variable
  PROJECT_NAME: arduino-lint
  # As defined by the Taskfile's DIST_DIR variable
  DIST_DIR: dist

jobs:
  run-determination:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.determination.outputs.result }}
    permissions: {}
    steps:
      - name: Determine if the rest of the workflow should run
        id: determination
        run: |
          RELEASE_BRANCH_REGEX="refs/heads/[0-9]+.[0-9]+.x"
          TAG_REGEX="refs/tags/.*"
          # The `create` event trigger doesn't support `branches` filters, so it's necessary to use Bash instead.
          if [[
            ("${{ github.event_name }}" != "create" ||
            "${{ github.ref }}" =~ $RELEASE_BRANCH_REGEX) &&
            ! "${{ github.ref }}" =~ $TAG_REGEX
          ]]; then
            # Run the other jobs.
            RESULT="true"
          else
            # There is no need to run the other jobs.
            RESULT="false"
          fi

          echo "result=$RESULT" >>$GITHUB_OUTPUT

  package-name-prefix:
    needs: run-determination
    if: needs.run-determination.outputs.result == 'true'
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      prefix: ${{ steps.calculation.outputs.prefix }}
    steps:
      - name: package name prefix calculation
        id: calculation
        run: |
          PACKAGE_NAME_PREFIX="test"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PACKAGE_NAME_PREFIX="$PACKAGE_NAME_PREFIX-${{ github.event.number }}"
          fi
          PACKAGE_NAME_PREFIX="$PACKAGE_NAME_PREFIX-${{ github.sha }}-"

          echo "prefix=$PACKAGE_NAME_PREFIX" >>$GITHUB_OUTPUT

  build:
    needs: package-name-prefix
    name: Build ${{ matrix.os.artifact-name }}
    runs-on: ${{ matrix.os.runner }}
    permissions:
      contents: read

    strategy:
      matrix:
        os:
          - task: Windows_32bit
            path: "*Windows_32bit.zip"
            runner: ubuntu-latest
            artifact-name: Windows_X86-32
          - task: Windows_64bit
            path: "*Windows_64bit.zip"
            runner: ubuntu-latest
            artifact-name: Windows_X86-64
          - task: Windows_ARM64
            path: "*Windows_ARM64.zip"
            runner: ubuntu-24.04-arm
            artifact-name: Windows_ARM64
          - task: Linux_32bit
            path: "*Linux_32bit.tar.gz"
            runner: ubuntu-latest
            artifact-name: Linux_X86-32
          - task: Linux_64bit
            path: "*Linux_64bit.tar.gz"
            runner: ubuntu-latest
            artifact-name: Linux_X86-64
          - task: Linux_ARMv6
            path: "*Linux_ARMv6.tar.gz"
            runner: ubuntu-latest
            artifact-name: Linux_ARMv6
          - task: Linux_ARMv7
            path: "*Linux_ARMv7.tar.gz"
            runner: ubuntu-latest
            artifact-name: Linux_ARMv7
          - task: Linux_ARM64
            path: "*Linux_ARM64.tar.gz"
            runner: ubuntu-24.04-arm
            artifact-name: Linux_ARM64
          - task: macOS_64bit
            path: "*macOS_64bit.tar.gz"
            runner: ubuntu-latest
            artifact-name: macOS_64
          - task: macOS_ARM64
            path: "*macOS_ARM64.tar.gz"
            runner: ubuntu-24.04-arm
            artifact-name: macOS_ARM64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          PACKAGE_NAME_PREFIX=${{ needs.package-name-prefix.outputs.prefix }}
          export PACKAGE_NAME_PREFIX
          go tool \
            github.com/go-task/task/v3/cmd/task dist:${{ matrix.os.task }}

      # Transfer builds to artifacts job
      - name: Upload build artifact
        uses: actions/upload-artifact@v5
        with:
          path: ${{ env.DIST_DIR }}/${{ matrix.os.path }}
          name: ${{ matrix.os.artifact-name }}

  checksums:
    needs:
      - build
      - package-name-prefix
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v7

      - name: Create checksum file
        run: |
          TAG="${{ needs.package-name-prefix.outputs.prefix }}git-snapshot"

          declare \
            -a \
            artifacts=($(ls -d */))

          for artifact in ${artifacts[@]}; do
            cd $artifact
            checksum=$(sha256sum ${{ env.PROJECT_NAME }}_${TAG}*)
            cd ..
            echo $checksum >>${TAG}-checksums.txt
          done

      - name: Upload checksum artifact
        uses: actions/upload-artifact@v5
        with:
          path: ./*checksums.txt
          name: checksums
